opensourcewebsite-org/opensourcewebsite-org

tests/unit/models/SignupFormTest.php
* Signup without giving email & password
* Signup with an email that is already in use
* Signup with valid credentials
* Checks whether confirmation email send or not
=> implements codeception unit test for signup page

controllers/SiteController.php, views/layouts/adminlte-guest.php, views/site/login-ajax.php, views/site/login.php, views/site/requestPasswordResetToken.php, views/site/signup.php, widgets/Alert.php
In controllers/SiteController.php
Altered actionResetPassword and actionSignup to be accessed only by ajax request
Updated actionLogin to be accessed by ajax or common request
In views/layouts/adminlte-guest.php
Added modal
Updated menu options
Created views/site/login-ajax.php to render when actionLogin is called via ajax request
In views/site/login.php
Change the link "reset it" to call the modal form
In views/site/requestPasswordResetToken.php, views/site/signup.php
Updated to be rendered via renderAjax
In widgets/Alert.php
Added 'show' class in class options
=> Added modal

assets/AdminLteAsset.php, assets/AdminLteGuestAsset.php, assets/FontAwesomeAsset.php, composer.json, views/layouts/adminlte-guest.php, views/layouts/adminlte-main.php, widgets/NavBar.php
Removed navbar-header
Created widgets/NavBar.php to remove the navbar-header generation
In views/layouts/adminlte-guest.php, views/layouts/adminlte-main.php
Modified to use the new NavBar
=> #5 Remove navbar header

assets/AdminLteAsset.php, assets/AdminLteGuestAsset.php, assets/FontAwesomeAsset.php, composer.json, views/layouts/adminlte-guest.php, views/layouts/adminlte-main.php
In assets/AdminLteAsset.php, assets/AdminLteGuestAsset.php
Removed line including fontawesome v4
In assets/FontAwesomeAsset.php
Modified route to point to fontawesome v5
In composer.json
Removed fontawesome v4
Added fontawesome v5
In views/layouts/adminlte-guest.php, views/layouts/adminlte-main.php
Added use of FontAwesomeAsset
After this change is needed to do a composer update so fontawesome v4 is removed from vendor and fontawesome v5 is added
=> #4 Removed fontawesome 4 and added fontawesome 5

controllers/UserController.php, views/layouts/adminlte-main.php, views/user/display.php
=> Display registered users

config/web.php, controllers/DataController.php, models/Country.php, models/Currency.php, views/data/country.php, views/data/currency.php, views/data/language.php, views/layouts/adminlte-main.php
=> Implements data model for Country, Currency & Language

controllers/MoqupController.php, migrations/m180826_031345_user_unsigned_id.php, migrations/m180826_031932_add_moqup_fk.php, migrations/m180826_032154_add_css_fk.php, models/Css.php, models/Moqup.php, models/MoqupSearch.php, views/moqup/design-edit.php, views/moqup/design-list.php
Created m180826_031345_user_unsigned_id
To change the user table id to unsigned
Created m180826_031932_add_moqup_fk
It adds the foreign key to the column user_id, referencing the user table id
Created m180826_032154_add_css_fk
It adds the foreign key to the column moqup_id, referencing the moqup table id
In models/Moqup, models/Css
Added functionality and validations
Created MoqupSearch
In MoqupController
Removed captcha action
Updated designList, designView actions
Merged designEdit, designAdd actions
Added designDelete action
In views/moqup/design-list
Added yii Gridview
Added pjax
Changed some code to yii style
In views/moqup/design-edit
Adapted to work registering and updating records
views/moqup/design-add is not used anymore
=> Issue 2 code

controllers/MoqupController.php, views/layouts/adminlte-moqup-preview.php, views/moqup/design-edit.php, views/moqup/design-preview.php
In controllers/MoqupController.php
Added designPreview action
Created views/layouts/adminlte-moqup-preview.php
Layout to show the content without navs, sidebar and footer
In views/moqup/design-edit.php
Added preview iframe and the script to insert the preview content
Created views/moqup/design-preview.php
Includes a container to insert the preview content
=> #26 Moqup preview tag working

controllers/DataController.php, models/Setting.php, views/data/setting.php, views/layouts/adminlte-main.php
=> implements setting data model

migrations/m180826_155342_fix_user_id.php
Fixed auto increment issue in user id
=> Fixed autoincrement user id

views/moqup/design-add.php, views/moqup/design-edit.php
Font Awesome 5 link added to add and edit moqups pages
=> fontawesome link added

assets/AceEditorAsset.php, assets/AceEditorStyleAsset.php, assets/EmmetAsset.php, composer.json, composer.lock, views/moqup/design-edit.php, web/css/ace-editor.css, web/js/emmet-core/emmet.js
Added assets/AceEditorAsset.php
To load AceEditor plugin
Added assets/AceEditorStyleAsset.php
To define AceEditor container style
Added assets/EmmetAsset.php
To load Emmet
In composer.json, composer.lock
Added AceEditor
In views/moqup/design-edit.php
Added AceEditor to html and css tabs
Added web/css/ace-editor.css
With the AceEditor container style
Added web/js/emmet-core/emmet.js
Emmet
=> Add embeddable code editor #40

views/wiki-tokens/form.php, views/wikipedia-pages/index.php
=> remove delete button & moved to update modal popup

models/MoqupSearch.php, web/css/site.css
In models/MoqupSearch.php
Added the default sort
In web/css/site.css
Updated the icon generated when sorting from glyphicon to fontawesome
(glyph was removed from bootstrap since v4)
=> Changed moqup list default sort

controllers/MoqupController.php, models/Css.php, models/Moqup.php, models/User.php
=> Added size validation

controllers/MoqupController.php, controllers/WikiTokensController.php, views/wiki-tokens/form.php
In views/wiki-tokens/form.php
The form was updated so now it don't make an ajax call when language is changed, the username and token inputs now are loaded with the language dropdown
In controllers/WikiTokensController.php
Adapted the actions "create" and "update"
=> Fix wikipedia watchlist

components/Converter.php, controllers/DataController.php, controllers/MoqupController.php, controllers/SiteController.php, controllers/UserController.php, controllers/WikipediaPagesController.php, migrations/m181007_154025_drop_rating_column_from_user_table.php, migrations/m181007_154209_create_rating_table.php, migrations/m181007_155114_upgrade_user_rating.php, models/Rating.php, models/User.php, views/site/account.php
In components/Converter.php
Added function to calculate percentage, and format numbers
In controllers/DataController.php, controllers/MoqupController.php, controllers/UserController.php, controllers/WikipediaPagesController.php
Added validation to allow access just to users with a confirmed email
In controllers/SiteController.php
After confirm email, the user rating is updated
In models/User.php
Added function to get the current user rating
In views/site/account.php
Added rating and ranking
Added models/Rating.php
Added the required migrations
=> User Rating

models/User.php
=> fix query active rating

components/WikiParser.php
That dropping user's pages in parser
=> delete only necessary pages in parser

components/WikiParser.php
* It must pass test before, because there are lot's of logic
* removed curl => used better lib new Client (yiisoft base)
* added error catch: if user changed his token or username
* refactored code
=> updated code in wiki parser removed curl function

models/SupportGroup.php
=> fixed support group create

controllers/WebhookController.php, models/SupportGroupCommand.php
=> send messages on choosen commands in telegram

controllers/WebhookController.php, models/BotHandler.php
* Default answer is taken from DB
=> fixed bug where default answer is setted in DB

controllers/WebhookController.php, models/BotHandler.php
=> Bug fix default commands

controllers/SupportGroupsController.php, models/search/SupportGroupSearch.php
=> all the support groups are private

controllers/SupportGroupsController.php, models/SupportGroupCommand.php, views/support-groups/commands/_edit_command.php, views/support-groups/commands/_edit_text.php, views/support-groups/view-command.php
=> Fix bug commands

controllers/SupportGroupsController.php
=> Bug access commands for members

controllers/WebhookController.php, migrations/m190117_144651_rename_support_group_client_bot_table.php, migrations/m190117_161226_add_support_group_bot_client_idx.php, models/BotHandler.php, models/SupportGroupBotClient.php, models/SupportGroupClient.php
enter /lang
and answer the question
=> languages setter command

controllers/WebhookController.php, migrations/m190118_130541_update_support_group_client_table.php, models/BotHandler.php, models/SupportGroupClient.php
-added proxy as a param
-user set up language on first command
=> logics for starters. If language not set

controllers/SupportGroupsController.php, migrations/m190118_151435_add_update_fields_in_support_group_command_text_table.php, models/SupportGroupCommandText.php, views/support-groups/commands/_edit_text.php
=> added new fields in BD and added security for update text

views/support-groups/view-command.php
=> fixed text page break

controllers/WebhookController.php, migrations/m190119_113822_add_first_name_last_name_to_support_group_bot_client_table.php, models/BotHandler.php, models/SupportGroupBotClient.php
- first_name
-last_name
and fixed blocked users.
=> Fix username client

config/web.php, controllers/SupportGroupsController.php, migrations/m190122_112049_add_description_to_support_group_bot_client.php, models/SupportGroupBotClient.php, models/SupportGroupClient.php, models/SupportGroupOutsideMessage.php, models/search/SupportGroupOutsideMessageSearch.php, views/support-groups/clients-languages.php, views/support-groups/clients-list.php, views/support-groups/clients/_edit_description.php, views/support-groups/clients/_messages.php, views/support-groups/index.php, views/support-groups/view-client.php
- added description
- added messages view logic
=> fixes view clients page

models/SupportGroupBotClient.php, views/support-groups/view-client.php
=> clients list fixes

controllers/SupportGroupsController.php, models/SupportGroupInsideMessage.php, models/search/SupportGroupOutsideMessageSearch.php, views/support-groups/clients/_messages.php, views/support-groups/view-client.php
=> messages from member in chat

controllers/SupportGroupsController.php, controllers/WebhookController.php, models/BotHandler.php, models/search/SupportGroupOutsideMessageSearch.php, views/support-groups/clients-list.php, views/support-groups/view-client.php
- Clients view fixes
- Cliens blocked fixes
- Bot API fixes (languages)
=> Fix clients 3

commands/CronController.php, models/CronJobConsole.php
=> changed logic of master cron

composer.json, composer.lock
=> updated yii 2.0.16 version

migrations/m190207_165555_add_new_settings_in_setting_table.php
=> added new setting

config/setting_validations.php, models/User.php
=> new setting added in code

commands/WikinewsParserController.php
Fix error with parsing wikinews.
Fix incorrect check of title a translation of record.
=> Fix bugs with wikinews parser

controllers/WikinewsPagesController.php, models/WikiUrlForm.php, models/WikinewsPage.php, views/wikinews-pages/form.php
=> remove Url property

models/BotHandler.php
If there is one language in the group, command /lang will return the default response. If there is one language in the group and the /lang command is setting, then when it is called, it will return the setting response
=> Fix bug for a command /lang.

models/BotHandler.php
Reverts opensourcewebsite-org/opensourcewebsite-org#197
=> Revert "Fix bug for a command /lang."

config/web.php, controllers/SupportGroupsController.php
Fix bug for client routing in group when only one language
=> Fix bug for client routing in group when only one language

config/web.php, controllers/SupportGroupsController.php, models/BotHandler.php
If there is one language in the group, command /lang will return the default response. If there is one language in the group and the /lang command is setting, then when it is called, it will return the setting response
=> Fix bug for a command /lang

models/BotHandler.php, views/support-groups/commands/_edit_command.php
Fix bug to create a new customer for a new group
=> Fix bug to create a new customer for a new group

config/db.php, config/web.php, views/support-groups/commands/_edit_text.php
=> implement emoji input for textarea field

views/support-groups/index.php
=> support group | change confirm window

composer.json, composer.lock, controllers/DebtController.php, migrations/m190706_130630_create_debt_table.php, models/Debt.php, views/debt/_form.php, views/debt/create.php, views/debt/credit.php, views/debt/deposit.php, views/debt/index.php, views/debt/update.php, views/debt/view.php, views/layouts/adminlte-main.php
=> implement debt

models/User.php
Reverts opensourcewebsite-org/opensourcewebsite-org#222
=> Revert "fix contact update"

commands/BotController.php, config/console.php, config/params.dist.php, controllers/WebhookController.php, migrations/m191021_071112_create_bot_table.php, migrations/m191021_071129_create_bot_client_table.php, migrations/m191021_071156_create_bot_outside_message_table.php, migrations/m191021_071206_create_bot_inside_message_table.php, models/Bot.php, models/BotClient.php, models/BotInsideMessage.php, models/BotOutsideMessage.php, models/SupportGroupBotHandler.php, models/TelegramBotHandler.php
Add basic support for telegram bot
=> Add basic support for telegram bot

controllers/SupportGroupsController.php, views/support-groups/commands/_edit_text.php
When the user creates a support group, you need to automatically create a "/start" command, in all languages that are connected to the support group, with the message "Welcome!". This command will automatically enable the value "Is default".
Fixed
=> fixes for part 1

controllers/SupportGroupsController.php, views/support-groups/commands/_edit_text.php
Fixes for support groups "/support-groups
=> Fixes for support groups "/support-groups

controllers/SupportGroupsController.php, views/support-groups/commands/_edit_text.php
=> Resize Fixes for command 

web/css/agency-fix.css
=> language dropdown styles fix

web/css/agency-fix.css
=> outline fix

models/SupportGroupLanguage.php
*checkboxList* method that is called from /views/support-groups/_form.php return an array value (that will contain language_codes in this case). So if we want to support multiple selection we must change rules of model app\models\SupportGroupLanguage taking into account that 'language_code' can be array value.
=> Saving multiple languages in support group editing works correctly

modules/bot/controllers/privates/My_genderController.php, modules/bot/controllers/privates/My_ratingController.php
=> Minor fixes

modules/bot/controllers/privates/My_emailController.php, modules/bot/controllers/privates/My_locationController.php, modules/bot/views/privates/my_birthday/create.php, modules/bot/views/privates/my_location/update.php
=> MyEmailController fix 

modules/bot/controllers/privates/My_emailController.php
=> /my_email setting new email fix

modules/bot/controllers/privates/My_emailController.php, modules/bot/models/UserState.php
=> Merge accounts fix

modules/bot/Module.php, modules/bot/controllers/privates/My_emailController.php
=> in process

mail/mergeAccountsRequest-text.php
=> Merge accounts email fix

modules/bot/controllers/privates/My_referralsController.php
=> Disable web page preview for /my_referrals command

modules/bot/controllers/privates/My_genderController.php, modules/bot/controllers/privates/My_profileController.php, modules/bot/views/privates/my_profile/index.php
=> Fix of /my_profile command

modules/bot/config.php, modules/bot/controllers/privates/AdminController.php, modules/bot/controllers/privates/Admin_message_filter_blacklistController.php, modules/bot/controllers/privates/Admin_message_filter_whitelistController.php, modules/bot/controllers/publics/MessageController.php, modules/bot/models/Chat.php
=> Pagination

controllers/SiteController.php
=> Signup bug

controllers/SiteController.php, models/SignupForm.php
=> Email confirming

modules/bot/components/CommandRouteResolver.php
=> Fix logging

modules/bot/components/CommandRouteResolver.php
=> CommandRouteResolver fix

modules/bot/views/privates/my-profile/index.php
=> MyProfile fix

modules/bot/components/response/commands/DeleteMessageCommand.php, modules/bot/controllers/privates/MyLanguagesController.php
=> MyLanguages add language fix

modules/bot/controllers/privates/VacanciesController.php
=> Fix of 'Back' button on editing vacancy screen

modules/bot/Module.php
=> Groups filter fix

CONTRIBUTING.md, INSTALL.md, controllers/ContactController.php, models/Debt.php, models/User.php
Added `REVIEW` comments. 
And description of their purpose into `*.md` files.
=> Code REVIEW [ci skip]

controllers/UserController.php, models/queries/UserQuery.php, views/user/display.php
Fix user count display.
Fix language statistic pages.
=> fix(user): statistic

.github/workflows/php.yml, modules/guest/views/layouts/main.php
Добавлен небольшой javascript код для упрощение выбора языка на главной странице в выпадающем списке языков. То есть, при наборе в поле ввода, ищет совпадение в списке доступных языков. Если есть какие либо совпадение, то другие в списке, пункты языков скрываются а найденные выводятся для выбора.
=> Добавлен небольшой JS код

models/User.php
=> Empty username fix

modules/bot/Module.php, modules/bot/components/CommandRouteResolver.php, modules/bot/config/public.php, modules/bot/controllers/privates/MyProfileController.php
=> Handling commands like "/command@botnamebot"

models/User.php, views/layouts/adminlte-user.php, web/css/adminlte-fix.css
Добавлена возможность поиска и выборки языка на странице аккаунта.
=> Добавлена возможность удобной выборки языка на странице аккаунта

views/site/account.php, views/user/fields/change-birthday.php
=> Profile fixes

composer.json, composer.lock, controllers/ContactController.php, controllers/SiteController.php, controllers/UserController.php, views/contact/view.php, views/site/account.php, views/user/profile.php
=> Real confirmation

docker-compose.yml
Use docker image mysql:5.7 --> mysql:8
=> Update to mysql 8

views/contact/view.php, views/support-groups/_form.php
=> add buttons

web/css/site.css
=> body add style position releative

requirements.php
fix #400 Improve requirements.php
Description of the Change
MySQL checking database version
Alternate Designs
Benefits
Possible Drawbacks
Verification Process
Applicable Issues
=> Improve requirements.php

docker-compose.yml
=> Update docker-compose to php7.4

views/examples/widgets.php
Replace paths in html elements
=> fix 404 error, change page path

controllers/SupportGroupsController.php, models/SupportGroupBot.php, models/SupportGroupInsideMessage.php, views/support-groups/view-client.php, widgets/buttons/SendButton.php
- Add send button (grey)
- Server side validation instead client side
- Fix url for bot webhook
- Delete flash message about success send message
=> Support groups fixes

ARCHITECTURE.ru.md, CONTRIBUTING.md, CONTRIBUTING.ru.md, INSTALL.ru.md
- Add russian documentation (translate)
- Add new records to eng documentation
=> translate documentation

components/debt/Redistribution.php, controllers/ContactController.php, models/Contact.php, models/queries/ContactQuery.php, modules/dataGenerator/components/generators/ContactFixture.php, views/contact/_form.php, views/contact/create.php, views/contact/index.php, views/contact/view.php
Meaning of case when `contact.debt_redistribution_priority = 0` changed:
- **was:** lowest priority (i.e. priority=256)
- **become:** deny to redistribute into this Contact
#294
=> ftr: change meaning of Contact.debt_redistribution_priority = 0

components/debt/BalanceChecker.php, composer.json, composer.lock
**Bug:** [command `yii debt/check-balance` has reported about errors in DB](https://opensourcewebsite.slack.com/archives/C0124M5AZGT/p1590394926000100). 
**Solution:** Problem was not in DB, but in checker. Way of comparison float numbers was wrong.
**Fixed**.
**Additional about problem:** https://stackoverflow.com/questions/3148937/compare-floats-in-php
#294
=> fix: BalanceChecker comparison of float numbers

views/layouts/adminlte-user.php, web/css/site.css
Move language menu styles from views/layouts/adminlte-user.php to web/css/site.css
=> Move language menu styles

modules/bot/controllers/privates/SAdOfferController.php, modules/bot/controllers/privates/SAdSearchController.php
=> Fix some moments

views/layouts/adminlte-guest.php, web/css/agency-fix.css
Move language menu styles from adminlte-guest.php to agency-fix.css
=> Move lang menu styles

modules/bot/config/private.php, modules/bot/controllers/privates/MyLocationController.php
=> Fix location

controllers/UserController.php, models/Rating.php, views/site/account.php, views/user/details/rating.php
Show for the user in his account the history of replenishment of his rating. On a separate tab or separate page. On the page use pagination for 20 entries, sort from new to old.
Names for transaction types: 2 = Donation, 1 = Contribution, 0 = Registration.
=> #449 Rating transactions

components/debt/Reduction.php, migrations/m200620_132139_alter_debt_balance_rename_processed_at_into_reduction_try_at.php, migrations/m200621_064129_alter_debt_balance_modify_redistribute_try_at_null.php, models/Debt.php, models/DebtBalance.php, models/DebtRedistribution.php, models/queries/DebtBalanceQuery.php, models/traits/FloatAttributeTrait.php, tests/_support/debt/redistribution/Common.php, tests/functional/debt/redistribution/RedistributionMaxAmountCest.php, tests/functional/debt/redistribution/RedistributionPriorityCest.php, tests/functional/debt/redistribution/RedistributionTargetBalanceHasOwnChainCest.php
Refactoring: https://opensourcewebsite.slack.com/archives/C0124M5AZGT/p1592576286001600
#294
=> 294 rename db col

components/debt/Reduction.php
=> #294 fix: app\components\debt\Reduction

models/Resume.php, models/Vacancy.php, modules/bot/components/crud/CrudController.php, modules/bot/components/crud/rules/LocationToArrayFieldComponent.php, modules/bot/controllers/privates/ResumeController.php, modules/bot/controllers/privates/SAdOfferController.php, modules/bot/controllers/privates/SJobController.php, modules/bot/controllers/privates/VacancyController.php, modules/bot/views/privates/resume/set-location.php, modules/bot/views/privates/resume/set-remote_on.php, modules/bot/views/privates/resume/set-search_radius.php, modules/bot/views/privates/resume/show.php, modules/bot/views/privates/vacancy/index.php, modules/bot/views/privates/vacancy/set-location.php, modules/bot/views/privates/vacancy/set-remote_on.php, modules/bot/views/privates/vacancy/show.php
* small fixes
* possible to switch off required field which have relation
* active vacancies
* remote Job
* text changes
* add location to resume and vacancy
* add radius to resume
* split buttons from config
=> milestone 2. part 1

migrations/m200702_094703_change_fkeys_for_offer_and_search_tables.php, modules/bot/components/crud/rules/LocationToArrayFieldComponent.php, modules/bot/controllers/privates/SAdOfferController.php
исправлено
* bug. в добавлении offer/search, на шаге Доставки нельзя выбрать “Нет“. Кнопка игнорится.
* bug. в создании offer на шаге Location нет кнопки “Моя геолокация“. Хотя в редактировании обьекта есть и это правильно, так как локация задана в профиле пользователя.
* bug. в редактировании локации в резюме (возможно и в вакансии) кнопка “Нет” не очищает ранее сохраненную локацию
=> milestone 2. bugs 1

components/debt/Redistribution.php, components/debt/Reduction.php, controllers/SiteController.php
=> refactoring: clean logs

config/web.php, models/Company.php, models/Resume.php, models/Vacancy.php, modules/bot/components/crud/services/AttributeButtonsService.php, modules/bot/controllers/privates/CompanyController.php, modules/bot/controllers/privates/MyLanguagesController.php, modules/bot/controllers/privates/ResumeController.php, modules/bot/controllers/privates/SAdOfferController.php, modules/bot/controllers/privates/SAdSearchController.php, modules/bot/controllers/privates/VacancyController.php, modules/bot/views/privates/resume/status-error.php, modules/bot/views/privates/vacancy/status-error.php
=> milestone 2. part 5

models/Resume.php, modules/bot/controllers/privates/ResumeController.php, modules/bot/controllers/privates/VacancyController.php
=> milestone 2. part 7

models/Resume.php, models/Vacancy.php, modules/bot/controllers/privates/ResumeController.php, modules/bot/controllers/privates/VacancyController.php
=> Milestone2p8

models/Company.php
=> milestone 2. part 9

DONATE.ru.md
=> text correction

modules/bot/controllers/privates/AdminChatController.php
Fixes issue 483 - Add Red Cross image in disabled chat functions
=> #483 Telegram bot for groups - add icon for turned off functions

commands/UaLawmakingParserController.php
=> UA Lawmaking parser

INSTALL.md, INSTALL.ru.md
=> Intall Fix

assets/widgets/forms/AdvancedElementsAsset.php
=> fix assets of examples/forms/advanced-elements

assets/LeafletLocateControlAsset.php, composer.json, models/CurrencyExchangeOrder.php, views/currency-exchange-order/_form.php, views/currency-exchange-order/index.php, views/currency-exchange-order/view.php, views/currency-exchange-order/view_offer.php, views/currency-exchange-order/view_offers.php
'my location' in location modal, allow empty sell/buy rates.
=> 'my location' in location modal, allow empty rates

assets/LeafletLocateControlAsset.php, controllers/CurrencyExchangeOrderController.php, migrations/m210319_061451_alter_currency_exchange_order_table.php, models/CurrencyExchangeOrder.php, modules/dataGenerator/components/generators/CurrencyExchangeOrderFixture.php, views/currency-exchange-order/_cash_method.php, views/currency-exchange-order/_form.php, views/currency-exchange-order/map_modal.php, views/currency-exchange-order/view.php
Splitting location and radius to selling location/radius and buying location/radius
=> Currency exchange split location to buy location sell location

controllers/ExamplesController.php, views/examples/mysql-info.php
=> fix mysql info

modules/bot/components/helpers/MessageWithEntitiesConverter.php
Fix errors:
* links at the end of line diffused newline character
* several links in a line: first link diffused the next.
=> Fix errors with links in message (bot)

.gitignore, INSTALL.md, INSTALL.ru.md
1. Add PHP CS Fixer config cache to .gitignore
2. Mention [Localtunnel ~ Expose yourself to the world](https://localtunnel.me/) in INSTALL
=> PHP CS Fixer config cache → .gitignore; Localtunnel → INSTALL

commands/StellarController.php, composer.lock, models/StellarServer.php
* Add some phpdocs
* Encapsulate saving income data to DB into StellarServer;
* Change interface of sendIncomeToAssetHolders: now it consumes UserStellarIncome[] and produces aggregated data about transactions instead of by operation. Also it includes saving info about operations' results;
* Encapsulate checking if date is payment date into StellarServer by isPaymentDate function;
* Change StellarController according to changes in StellarServer;
* Add fetching asset holders from DB after saving it, instead of direct use
* Fix checking date of timestamp
* Use method instead of Yii app params array
* Update php-stellar-sdk
=> Stellar Send deposit income

composer.lock, models/StellarServer.php
=> Stellar add ledger check

models/StellarCroupier.php
If getPayments() returns no bets but other operations, they are not processed again in next call of processBets().
=> Fix processBets(): now paging token updates despite type of operation got from getPayments()

assets/EmmetAsset.php, assets/widgets/CommonAsset.php, assets/widgets/dashboard/VisitorsAsset.php, assets/widgets/ui/TabsAsset.php, assets/widgets/ui/TimelineAsset.php, config/web.php, views/examples/charts/chartjs.php, views/examples/dashboard/1.php, views/examples/dashboard/2.php, views/examples/dashboard/3.php, views/examples/ui-elements/ribbons.php, views/examples/ui-elements/sliders.php, views/examples/ui-elements/timeline.php
Общие изменения: 
- Основное изменение: в проекте Jquery подключался 2 раза - это в assets/widgets/CommonAsset.php и в config/web.php; решил отталкиваться от того, что был подключён в конфиге (он посвежее и подключается от cdn, также подключил его в конец скрипта), в ассетах отключил. 
- 2й момент - в файлах представлениях скрипты поместил в отдельный блок и подключил их в конец, после файлов ассетов. 
Частные изменения:
- assets/EmmetAsset.php - на одной из страниц консоль показывала ошибку, закомментировал ресурс и ошибка ушла;
- assets/widgets/dashboard/VisitorsAsset.php - на странице /examples/dashboard/1 была ошибка со ссылкой на данный файл (в скрипте на строке 531), никак не получалось убрать. В итоге пришёл к выводу, что данный ресурс и код не подходят друг другу, код …
=> Для всех страниц(кроме /examples/ui-elements/general) исправлены ошибки консоли

composer.lock, controllers/DebtController.php, views/debt/_form.php, widgets/selects/ContactSelect.php
Changes have been made to the form for creating a debt so that an array of all contacts is not loaded in the contact selection field at once, but is loaded via ajax in portions.
Made in accordance with the recommendations for the for Yii 2 Select2 widget used on the project [Select2 jQuery plugin](https://select2.github.io/). https://demos.krajee.com/widget-details/select2#usage-ajax
=> select2 ajax pagination added for debt controller

web/css/agency-fix.css
=> fixed dropdown-menu

web/css/site.css
=>  Fix tags block

web/css/site.css
=> fix dropdown languges list

views/ad-search/matches.php
=> add float-right to btn 'eye'

models/SupportGroupBotHandler.php, modules/bot/components/api/Types/Message.php
=> bot - group - remove styled text - improve
